import React, { useState } from 'react'
import {
  View, Text, TextInput, TouchableOpacity, StyleSheet,
  ScrollView, ActivityIndicator, Alert, Share, Modal, Platform,
} from 'react-native'
import BackRow from '../components/BackRow'

const GREEN = '#1a3728'

interface Item { description: string; qty: string; price: string }

export default function PublicGenerateScreen({ navigation }: any) {
  const [sellerName, setSellerName] = useState('')
  const [sellerAddress, setSellerAddress] = useState('')
  const [buyerName, setBuyerName] = useState('')
  const [buyerEmail, setBuyerEmail] = useState('')
  const [buyerPhone, setBuyerPhone] = useState('')
  const [items, setItems] = useState<Item[]>([{ description: '', qty: '1', price: '0' }])
  const [notes, setNotes] = useState('Thank you for your business. We appreciate your trust and look forward to working with you again.')
  const [bankName, setBankName] = useState('')
  const [acctName, setAcctName] = useState('')
  const [acctNo, setAcctNo] = useState('')
  const [currency, setCurrency] = useState('NGN')
  const [showCurrencyOptions, setShowCurrencyOptions] = useState(false)
  const CURRENCIES = [
    { code: 'NGN', symbol: '₦', label: 'Nigerian Naira' },
    { code: 'USD', symbol: '$', label: 'US Dollar' },
    { code: 'GBP', symbol: '£', label: 'British Pound' },
    { code: 'EUR', symbol: '€', label: 'Euro' },
    { code: 'GHS', symbol: 'GH₵', label: 'Ghanaian Cedi' },
    { code: 'KES', symbol: 'KSh', label: 'Kenyan Shilling' },
    { code: 'ZAR', symbol: 'R', label: 'South African Rand' },
  ]
  const selectedCurrency = CURRENCIES.find(c => c.code === currency) || CURRENCIES[0]
  const [accepted, setAccepted] = useState<string[]>([])
  const [showPaymentOptions, setShowPaymentOptions] = useState(false)
  const PAYMENT_OPTIONS = ['Bank Transfer', 'Cash', 'POS', 'Crypto', 'Cheque']
  const [loading, setLoading] = useState(false)
  const [generated, setGenerated] = useState<any>(null)
  const [showPdf, setShowPdf] = useState(false)

  const invoiceNo = 'INV-' + Date.now().toString().slice(-8)
  const today = new Date().toLocaleDateString('en-GB')
  const [invoiceDate, setInvoiceDate] = useState(today)

  function addItem() {
    setItems([...items, { description: '', qty: '1', price: '0' }])
  }

  function updateItem(idx: number, field: keyof Item, val: string) {
    const updated = [...items]
    updated[idx] = { ...updated[idx], [field]: val }
    setItems(updated)
  }

  function removeItem(idx: number) {
    if (items.length === 1) return
    setItems(items.filter((_, i) => i !== idx))
  }

  function getTotal() {
    return items.reduce((sum, it) => {
      return sum + (parseFloat(it.qty) || 0) * (parseFloat(it.price) || 0)
    }, 0)
  }

  function getItemAmt(it: Item) {
    return (parseFloat(it.qty) || 0) * (parseFloat(it.price) || 0)
  }

  async function generate() {
    if (!sellerName.trim()) { Alert.alert('Required', 'Enter your business name.'); return }
    if (items.some(it => !it.description.trim())) {
      Alert.alert('Required', 'Fill in all item descriptions.'); return
    }
    setLoading(true)
    setTimeout(() => {
      setGenerated({ invoiceNo, today: invoiceDate, sellerName, sellerAddress, buyerName, buyerEmail, buyerPhone, items, total: getTotal(), notes, bankName, acctName, acctNo, accepted })
      setLoading(false)
    }, 400)
  }

  async function shareInvoice() {
    if (!generated) return
    const lines = [
      `INVOICE — ${generated.invoiceNo}`,
      `Date: ${generated.today}`,
      ``,
      `From: ${generated.sellerName}${generated.sellerAddress ? '\n' + generated.sellerAddress : ''}`,
      generated.buyerName ? `\nBilled To: ${generated.buyerName}` : '',
      generated.buyerEmail ? generated.buyerEmail : '',
      generated.buyerPhone ? generated.buyerPhone : '',
      ``,
      `ITEMS:`,
      ...generated.items.map((it: Item, i: number) =>
        `${i + 1}. ${it.description}  Qty: ${it.qty} x ₦${parseFloat(it.price).toLocaleString()} = ₦${getItemAmt(it).toLocaleString()}`
      ),
      ``,
      `TOTAL: ₦${generated.total.toLocaleString()}`,
      generated.notes ? `\nNotes: ${generated.notes}` : '',
      `\nGenerated by DigitalReceipt.ng`,
    ].filter(Boolean).join('\n')
    await Share.share({ message: lines, title: `Invoice ${generated.invoiceNo}` })
  }

  if (generated) {
    const PdfContent = () => (
      <ScrollView style={styles.pdfScroll} contentContainerStyle={{ padding: 24 }}>
        {/* Letterhead */}
        <View style={styles.pdfHeader}>
          <View>
            <Text style={styles.pdfInvoiceWord}>INVOICE</Text>
            <Text style={styles.pdfInvoiceNo}>{generated.invoiceNo}</Text>
            <Text style={styles.pdfDate}>Date: {generated.today}</Text>
          </View>
          <View style={{ alignItems: 'flex-end' }}>
            <Text style={styles.pdfBizName}>{generated.sellerName}</Text>
            {generated.sellerAddress ? <Text style={styles.pdfBizSub}>{generated.sellerAddress}</Text> : null}
          </View>
        </View>

        <View style={styles.pdfDivider} />

        {generated.buyerName ? (
          <View style={{ marginBottom: 16 }}>
            <Text style={styles.pdfSectionLabel}>BILLED TO</Text>
            <Text style={styles.pdfBuyerName}>{generated.buyerName}</Text>
            {generated.buyerEmail ? <Text style={styles.pdfBuyerSub}>{generated.buyerEmail}</Text> : null}
            {generated.buyerPhone ? <Text style={styles.pdfBuyerSub}>{generated.buyerPhone}</Text> : null}
          </View>
        ) : null}

        <View style={styles.pdfDivider} />

        {/* Items */}
        <View style={styles.pdfTableHead}>
          <Text style={[styles.pdfTableHeadTxt, { flex: 3 }]}>Description</Text>
          <Text style={[styles.pdfTableHeadTxt, { flex: 1, textAlign: 'center' }]}>Qty</Text>
          <Text style={[styles.pdfTableHeadTxt, { flex: 2, textAlign: 'right' }]}>Unit</Text>
          <Text style={[styles.pdfTableHeadTxt, { flex: 2, textAlign: 'right' }]}>Amount</Text>
        </View>
        {generated.items.map((it: Item, i: number) => (
          <View key={i} style={[styles.pdfTableRow, i % 2 === 0 && { backgroundColor: '#f9fafb' }]}>
            <Text style={[styles.pdfTableCell, { flex: 3 }]}>{it.description}</Text>
            <Text style={[styles.pdfTableCell, { flex: 1, textAlign: 'center' }]}>{it.qty}</Text>
            <Text style={[styles.pdfTableCell, { flex: 2, textAlign: 'right' }]}>₦{parseFloat(it.price).toLocaleString()}</Text>
            <Text style={[styles.pdfTableCell, { flex: 2, textAlign: 'right', fontWeight: '700' }]}>₦{getItemAmt(it).toLocaleString()}</Text>
          </View>
        ))}

        <View style={styles.pdfDivider} />

        <View style={styles.pdfTotalRow}>
          <Text style={styles.pdfTotalLabel}>TOTAL</Text>
          <Text style={styles.pdfTotalAmt}>₦{generated.total.toLocaleString()}</Text>
        </View>

        {(generated.bankName || generated.acctName || generated.acctNo || generated.accepted?.length > 0) ? (
          <>
            <View style={styles.pdfDivider} />
            <Text style={styles.pdfSectionLabel}>PAYMENT DETAILS</Text>
            {generated.bankName ? <Text style={styles.pdfPayLine}><Text style={styles.pdfPayKey}>Bank: </Text>{generated.bankName}</Text> : null}
            {generated.acctName ? <Text style={styles.pdfPayLine}><Text style={styles.pdfPayKey}>Account Name: </Text>{generated.acctName}</Text> : null}
            {generated.acctNo ? <Text style={styles.pdfPayLine}><Text style={styles.pdfPayKey}>Account No: </Text>{generated.acctNo}</Text> : null}
            {generated.accepted?.length > 0 ? <Text style={styles.pdfPayLine}><Text style={styles.pdfPayKey}>Accepted: </Text>{generated.accepted.join(', ')}</Text> : null}
          </>
        ) : null}

        {generated.notes ? (
          <>
            <View style={styles.pdfDivider} />
            <Text style={styles.pdfSectionLabel}>NOTES</Text>
            <Text style={styles.pdfNotes}>{generated.notes}</Text>
          </>
        ) : null}

        <View style={styles.pdfFooterBar}>
          <Text style={styles.pdfFooterTxt}>Generated by DigitalReceipt.ng</Text>
        </View>
      </ScrollView>
    )

    return (
      <ScrollView style={styles.container} contentContainerStyle={{ padding: 16 }}>
        {navigation && <BackRow navigation={navigation} />}
        {/* PDF Modal */}
        <Modal visible={showPdf} animationType="slide" onRequestClose={() => setShowPdf(false)}>
          <View style={{ flex: 1, backgroundColor: '#e5e7eb' }}>
            <View style={styles.pdfTopBar}>
              <TouchableOpacity onPress={() => setShowPdf(false)} style={styles.pdfCloseBtn}>
                <Text style={styles.pdfCloseTxt}>✕ Close</Text>
              </TouchableOpacity>
              <Text style={styles.pdfTopTitle}>Invoice Preview</Text>
              <TouchableOpacity onPress={shareInvoice} style={styles.pdfShareBtn}>
                <Text style={styles.pdfShareTxt}>Share</Text>
              </TouchableOpacity>
            </View>
            <View style={styles.pdfPage}>
              <PdfContent />
            </View>
          </View>
        </Modal>
        <View style={styles.invoiceCard}>
          {/* Header */}
          <View style={styles.invHeader}>
            <View>
              <Text style={styles.invTitle}>Invoice</Text>
              <Text style={styles.invNo}>{generated.invoiceNo}</Text>
            </View>
            <View style={{ alignItems: 'flex-end' }}>
              <Text style={styles.invBiz}>{generated.sellerName}</Text>
              {generated.sellerAddress ? <Text style={styles.invBizSub}>{generated.sellerAddress}</Text> : null}
              <Text style={styles.invDate}>{generated.today}</Text>
            </View>
          </View>

          <View style={styles.divider} />

          {/* Billed To */}
          {generated.buyerName ? (
            <>
              <Text style={styles.billedLabel}>BILLED TO</Text>
              <Text style={styles.buyerName}>{generated.buyerName}</Text>
              {generated.buyerEmail ? <Text style={styles.buyerSub}>{generated.buyerEmail}</Text> : null}
              {generated.buyerPhone ? <Text style={styles.buyerSub}>{generated.buyerPhone}</Text> : null}
              <View style={styles.divider} />
            </>
          ) : null}

          {/* Items table */}
          <View style={styles.tableHeader}>
            <Text style={styles.tableHeaderLeft}>Item / Service</Text>
            <Text style={styles.tableHeaderRight}>Amount</Text>
          </View>
          {generated.items.map((it: Item, i: number) => (
            <View key={i} style={styles.tableRow}>
              <View style={{ flex: 1 }}>
                <Text style={styles.tableDesc}>{i + 1}.  {it.description}</Text>
                <Text style={styles.tableQty}>Qty: {it.qty}  ×  ₦{parseFloat(it.price).toLocaleString()}</Text>
              </View>
              <Text style={styles.tableAmt}>₦{getItemAmt(it).toLocaleString()}</Text>
            </View>
          ))}

          <View style={styles.divider} />

          {/* Total */}
          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>Total</Text>
            <Text style={styles.totalAmt}>₦{generated.total.toLocaleString()}</Text>
          </View>

          {(generated.bankName || generated.acctName || generated.acctNo || generated.accepted?.length > 0) ? (
            <>
              <View style={styles.divider} />
              <Text style={styles.billedLabel}>PAYMENT DETAILS</Text>
              {generated.bankName ? <View style={styles.payRow}><Text style={styles.payKey}>Bank:</Text><Text style={styles.payVal}>{generated.bankName}</Text></View> : null}
              {generated.acctName ? <View style={styles.payRow}><Text style={styles.payKey}>Acct Name:</Text><Text style={styles.payVal}>{generated.acctName}</Text></View> : null}
              {generated.acctNo ? <View style={styles.payRow}><Text style={styles.payKey}>Acct No:</Text><Text style={styles.payVal}>{generated.acctNo}</Text></View> : null}
              {generated.accepted?.length > 0 ? <View style={styles.payRow}><Text style={styles.payKey}>Accepted:</Text><Text style={styles.payVal}>{generated.accepted.join(', ')}</Text></View> : null}
            </>
          ) : null}

          {generated.notes ? (
            <>
              <View style={styles.divider} />
              <Text style={styles.notesLabel}>NOTES</Text>
              <Text style={styles.notesText}>{generated.notes}</Text>
            </>
          ) : null}

          <Text style={styles.footer}>Generated by DigitalReceipt.ng</Text>
        </View>

        <TouchableOpacity style={styles.shareBtn} onPress={() => setShowPdf(true)}>
          <Text style={styles.shareBtnText}>👁  View Invoice</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.shareBtn} onPress={shareInvoice}>
          <Text style={styles.shareBtnText}>📤  Share Invoice</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.newBtn} onPress={() => { setGenerated(null); setShowPdf(false) }}>
          <Text style={styles.newBtnText}>Create New Invoice</Text>
        </TouchableOpacity>
      </ScrollView>
    )
  }

  return (
    <View style={{ flex: 1, backgroundColor: '#f5f5f5' }}>
    <ScrollView style={styles.container} contentContainerStyle={{ padding: 16, paddingBottom: 100 }}>
      {navigation && <BackRow navigation={navigation} />}
      {/* Invoice card preview / form */}
      <View style={styles.invoiceCard}>
        {/* Header */}
        <View style={styles.invHeader}>
          <View>
            <Text style={styles.invTitle}>Invoice</Text>
            <Text style={styles.invNo}>{invoiceNo}</Text>
          </View>
          <View style={{ alignItems: 'flex-end', flex: 1, marginLeft: 12 }}>
            <TextInput
              style={styles.headerInput}
              placeholder="Your Business Name"
              placeholderTextColor="#9ca3af"
              value={sellerName}
              onChangeText={setSellerName}
              textAlign="right"
            />
            <TextInput
              style={[styles.headerInput, { fontSize: 12 }]}
              placeholder="Business address"
              placeholderTextColor="#c4c4c4"
              value={sellerAddress}
              onChangeText={setSellerAddress}
              textAlign="right"
            />
            <TextInput
              style={[styles.headerInput, { fontSize: 13, color: '#374151' }]}
              value={invoiceDate}
              onChangeText={setInvoiceDate}
              placeholder="DD/MM/YYYY"
              placeholderTextColor="#9ca3af"
              textAlign="right"
              keyboardType="numbers-and-punctuation"
            />
          </View>
        </View>

        <View style={styles.divider} />

        {/* Billed To */}
        <Text style={styles.billedLabel}>BILLED TO</Text>
        <TextInput style={styles.billedInput} placeholder="Client / Company Name"
          placeholderTextColor="#9ca3af" value={buyerName} onChangeText={setBuyerName} />
        <TextInput style={styles.billedInput} placeholder="client@email.com (optional)"
          placeholderTextColor="#c4c4c4" value={buyerEmail} onChangeText={setBuyerEmail} keyboardType="email-address" />
        <TextInput style={styles.billedInput} placeholder="+234 80... (optional)"
          placeholderTextColor="#c4c4c4" value={buyerPhone} onChangeText={setBuyerPhone} keyboardType="phone-pad" />

        <TouchableOpacity style={styles.currencySelector} onPress={() => setShowCurrencyOptions(!showCurrencyOptions)}>
          <Text style={styles.currencyLabel}>Currency</Text>
          <View style={styles.currencyValue}>
            <Text style={styles.currencyText}>{selectedCurrency.symbol} — {selectedCurrency.label} ({selectedCurrency.code})</Text>
            <Text style={{ color: '#6b7280', fontSize: 12 }}>▾</Text>
          </View>
        </TouchableOpacity>
        {showCurrencyOptions && (
          <View style={styles.currencyOptionsWrap}>
            {CURRENCIES.map(c => (
              <TouchableOpacity key={c.code} style={[styles.currencyOption, currency === c.code && styles.currencyOptionActive]}
                onPress={() => { setCurrency(c.code); setShowCurrencyOptions(false) }}>
                <Text style={[styles.currencyOptionSymbol, currency === c.code && { color: '#fff' }]}>{c.symbol}</Text>
                <Text style={[styles.currencyOptionLabel, currency === c.code && { color: '#fff' }]}>{c.label}</Text>
                <Text style={[styles.currencyOptionCode, currency === c.code && { color: 'rgba(255,255,255,0.7)' }]}>{c.code}</Text>
              </TouchableOpacity>
            ))}
          </View>
        )}

        <View style={styles.divider} />

        {/* Items */}
        <View style={styles.tableHeader}>
          <Text style={styles.tableHeaderLeft}>Item / Service</Text>
          <Text style={styles.tableHeaderRight}>Amount</Text>
        </View>
        {items.map((item, idx) => (
          <View key={idx} style={styles.tableRow}>
            <View style={{ flex: 1 }}>
              <View style={{ flexDirection: 'row', alignItems: 'center' }}>
                <Text style={styles.itemNum}>{idx + 1}.</Text>
                <TextInput
                  style={styles.itemDescInput}
                  placeholder="Item description"
                  placeholderTextColor="#9ca3af"
                  value={item.description}
                  onChangeText={v => updateItem(idx, 'description', v)}
                />
                {items.length > 1 && (
                  <TouchableOpacity onPress={() => removeItem(idx)} style={{ padding: 4 }}>
                    <Text style={{ color: '#dc2626', fontSize: 16 }}>🗑</Text>
                  </TouchableOpacity>
                )}
              </View>
              <View style={styles.qtyRow}>
                <Text style={styles.qtyLabel}>Qty:</Text>
                <TextInput
                  style={styles.qtyInput}
                  value={item.qty}
                  onChangeText={v => updateItem(idx, 'qty', v)}
                  keyboardType="numeric"
                />
                <Text style={styles.qtyLabel}>  ×  Unit Price: {selectedCurrency.symbol}</Text>
                <TextInput
                  style={[styles.qtyInput, { flex: 1 }]}
                  value={item.price}
                  onChangeText={v => updateItem(idx, 'price', v)}
                  keyboardType="numeric"
                />
                <Text style={styles.qtyLabel}>  —</Text>
              </View>
            </View>
          </View>
        ))}

        <TouchableOpacity style={styles.addItemBtn} onPress={addItem}>
          <Text style={styles.addItemTxt}>+  Add item</Text>
        </TouchableOpacity>

        <View style={styles.divider} />

        <View style={styles.totalRow}>
          <Text style={styles.totalLabel}>Total</Text>
          <Text style={styles.totalAmt}>₦{getTotal().toLocaleString()}</Text>
        </View>
      </View>

      {/* Payment Details */}
      <View style={[styles.invoiceCard, { marginTop: 12 }]}>
        <Text style={styles.billedLabel}>PAYMENT DETAILS</Text>
        <View style={styles.payRow}>
          <Text style={styles.payKey}>Bank:</Text>
          <TextInput style={styles.payInput} placeholder="Bank name" placeholderTextColor="#c4c4c4"
            value={bankName} onChangeText={setBankName} />
        </View>
        <View style={styles.payRow}>
          <Text style={styles.payKey}>Acct Name:</Text>
          <TextInput style={styles.payInput} placeholder="Account name" placeholderTextColor="#c4c4c4"
            value={acctName} onChangeText={setAcctName} />
        </View>
        <View style={styles.payRow}>
          <Text style={styles.payKey}>Acct No:</Text>
          <TextInput style={styles.payInput} placeholder="Account number" placeholderTextColor="#c4c4c4"
            value={acctNo} onChangeText={setAcctNo} keyboardType="numeric" />
        </View>
        <View style={styles.payRow}>
          <Text style={styles.payKey}>Accepted:</Text>
          <TouchableOpacity style={styles.payDropdown} onPress={() => setShowPaymentOptions(!showPaymentOptions)}>
            <Text style={{ color: accepted.length ? '#374151' : '#c4c4c4', fontSize: 14, flex: 1 }}>
              {accepted.length ? accepted.join(', ') : 'Tap to select...'}
            </Text>
            <Text style={{ color: '#6b7280' }}>▾</Text>
          </TouchableOpacity>
        </View>
        {showPaymentOptions && (
          <View style={styles.optionsWrap}>
            {PAYMENT_OPTIONS.map(opt => (
              <TouchableOpacity
                key={opt}
                style={styles.optionRow}
                onPress={() => {
                  setAccepted(prev => prev.includes(opt) ? prev.filter(x => x !== opt) : [...prev, opt])
                  setShowPaymentOptions(false)
                }}
              >
                <Text style={styles.optionCheck}>{accepted.includes(opt) ? '☑' : '☐'}</Text>
                <Text style={styles.optionLabel}>{opt}</Text>
              </TouchableOpacity>
            ))}
          </View>
        )}
      </View>

      {/* Notes */}
      <View style={[styles.invoiceCard, { marginTop: 12 }]}>
        <Text style={styles.billedLabel}>NOTES</Text>
        <TextInput
          style={[styles.billedInput, { height: 80, textAlignVertical: 'top' }]}
          placeholderTextColor="#c4c4c4"
          value={notes}
          onChangeText={setNotes}
          multiline
        />
      </View>

    </ScrollView>
    <View style={styles.fixedGenBtn}>
      <TouchableOpacity style={[styles.shareBtn, loading && { opacity: 0.6 }]} onPress={generate} disabled={loading}>
        {loading ? <ActivityIndicator color="#fff" /> : <Text style={styles.shareBtnText}>Generate Invoice</Text>}
      </TouchableOpacity>
    </View>
    </View>
  )
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f5f5' },
  invoiceCard: { backgroundColor: '#fff', borderRadius: 14, padding: 20, shadowColor: '#000', shadowOpacity: 0.06, shadowRadius: 8, elevation: 3 },
  invHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  invTitle: { fontSize: 26, fontWeight: '900', color: '#111827' },
  invNo: { fontSize: 12, color: '#9a7c3f', marginTop: 2 },
  invBiz: { fontSize: 14, fontWeight: '700', color: '#6b7280', textAlign: 'right' },
  invBizSub: { fontSize: 12, color: '#9ca3af', textAlign: 'right' },
  invDate: { fontSize: 13, color: '#374151', marginTop: 4 },
  headerInput: { fontSize: 14, fontWeight: '600', color: '#6b7280', borderBottomWidth: 1, borderBottomColor: '#e5e7eb', paddingVertical: 2, minWidth: 140 },
  divider: { height: 1, backgroundColor: '#e5e7eb', marginVertical: 16 },
  billedLabel: { fontSize: 11, fontWeight: '800', color: '#1a3728', letterSpacing: 1.5, textTransform: 'uppercase', marginBottom: 8 },
  billedInput: { fontSize: 14, color: '#374151', borderBottomWidth: 1, borderBottomColor: '#f3f4f6', paddingVertical: 6, marginBottom: 6 },
  buyerName: { fontSize: 16, fontWeight: '700', color: '#111827', marginBottom: 2 },
  buyerSub: { fontSize: 13, color: '#6b7280' },
  tableHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  tableHeaderLeft: { fontSize: 13, fontWeight: '800', color: '#111827' },
  tableHeaderRight: { fontSize: 13, fontWeight: '800', color: '#111827' },
  tableRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 12 },
  tableDesc: { fontSize: 14, color: '#374151', fontWeight: '500' },
  tableQty: { fontSize: 12, color: '#6b7280', marginTop: 2 },
  tableAmt: { fontSize: 14, fontWeight: '700', color: '#111827', minWidth: 80, textAlign: 'right' },
  itemNum: { fontSize: 14, color: '#6b7280', marginRight: 4, marginTop: 4 },
  itemDescInput: { flex: 1, fontSize: 14, color: '#374151', borderBottomWidth: 1, borderBottomColor: '#f3f4f6', paddingVertical: 4 },
  qtyRow: { flexDirection: 'row', alignItems: 'center', marginTop: 6, marginLeft: 14 },
  qtyLabel: { fontSize: 13, color: '#6b7280' },
  qtyInput: { fontSize: 13, color: '#374151', borderBottomWidth: 1, borderBottomColor: '#e5e7eb', minWidth: 36, paddingVertical: 2, textAlign: 'center' },
  addItemBtn: { paddingVertical: 8 },
  addItemTxt: { fontSize: 14, color: '#1a3728', fontWeight: '700' },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  totalLabel: { fontSize: 16, fontWeight: '800', color: '#111827' },
  totalAmt: { fontSize: 18, fontWeight: '900', color: '#111827' },
  notesLabel: { fontSize: 11, fontWeight: '700', color: '#9ca3af', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 6 },
  notesText: { fontSize: 13, color: '#374151' },
  footer: { fontSize: 11, color: '#9ca3af', textAlign: 'center', marginTop: 20 },
  fixedGenBtn: { padding: 16, paddingBottom: Platform.OS === 'ios' ? 28 : 16, backgroundColor: '#f5f5f5', borderTopWidth: 1, borderTopColor: '#e5e7eb' },
  shareBtn: { backgroundColor: '#1a3728', borderRadius: 12, padding: 16, alignItems: 'center' },
  shareBtnText: { color: '#fff', fontWeight: '700', fontSize: 16 },
  newBtn: { borderWidth: 1, borderColor: '#1a3728', borderRadius: 12, padding: 14, alignItems: 'center', marginBottom: 30 },
  newBtnText: { color: '#1a3728', fontWeight: '700', fontSize: 14 },
  payRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  payKey: { fontSize: 13, fontWeight: '700', color: '#374151', width: 90 },
  payInput: { flex: 1, fontSize: 14, color: '#374151', borderBottomWidth: 1, borderBottomColor: '#f3f4f6', paddingVertical: 4 },
  payVal: { flex: 1, fontSize: 14, color: '#374151' },
  payDropdown: { flex: 1, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#f3f4f6', paddingVertical: 6 },
  optionsWrap: { backgroundColor: '#f9fafb', borderRadius: 10, padding: 10, marginTop: 4, marginLeft: 90 },
  optionRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 6 },
  optionCheck: { fontSize: 18, marginRight: 10, color: '#1a3728' },
  optionLabel: { fontSize: 14, color: '#374151' },
  currencySelector: { marginTop: 6, marginBottom: 2 },
  currencyLabel: { fontSize: 11, fontWeight: '700', color: '#1a3728', letterSpacing: 0.8, textTransform: 'uppercase', marginBottom: 4 },
  currencyValue: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: '#e5e7eb', paddingVertical: 8 },
  currencyText: { fontSize: 14, color: '#374151', fontWeight: '500' },
  currencyOptionsWrap: { backgroundColor: '#f9fafb', borderRadius: 10, marginTop: 4, overflow: 'hidden', borderWidth: 1, borderColor: '#e5e7eb' },
  currencyOption: { flexDirection: 'row', alignItems: 'center', paddingVertical: 11, paddingHorizontal: 14 },
  currencyOptionActive: { backgroundColor: '#1a3728' },
  currencyOptionSymbol: { fontSize: 15, fontWeight: '800', color: '#1a3728', width: 32 },
  currencyOptionLabel: { flex: 1, fontSize: 14, color: '#374151' },
  currencyOptionCode: { fontSize: 12, color: '#9ca3af', fontWeight: '600' },

  // PDF modal
  pdfTopBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#1a3728', paddingHorizontal: 16, paddingVertical: 14, paddingTop: 48 },
  pdfTopTitle: { color: '#fff', fontWeight: '700', fontSize: 16 },
  pdfCloseBtn: { padding: 6 },
  pdfCloseTxt: { color: '#fff', fontSize: 14 },
  pdfShareBtn: { backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: 8, paddingHorizontal: 14, paddingVertical: 6 },
  pdfShareTxt: { color: '#fff', fontWeight: '700', fontSize: 14 },
  pdfPage: { flex: 1, margin: 12, backgroundColor: '#fff', borderRadius: 4, shadowColor: '#000', shadowOpacity: 0.15, shadowRadius: 10, elevation: 6, overflow: 'hidden' },
  pdfScroll: { flex: 1, backgroundColor: '#fff' },
  pdfHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 4 },
  pdfInvoiceWord: { fontSize: 28, fontWeight: '900', color: '#1a3728', letterSpacing: 2 },
  pdfInvoiceNo: { fontSize: 12, color: '#9a7c3f', marginTop: 2 },
  pdfDate: { fontSize: 12, color: '#6b7280', marginTop: 4 },
  pdfBizName: { fontSize: 14, fontWeight: '700', color: '#111827', textAlign: 'right' },
  pdfBizSub: { fontSize: 11, color: '#6b7280', textAlign: 'right', marginTop: 2 },
  pdfDivider: { height: 1, backgroundColor: '#e5e7eb', marginVertical: 14 },
  pdfSectionLabel: { fontSize: 10, fontWeight: '800', color: '#1a3728', letterSpacing: 1.5, textTransform: 'uppercase', marginBottom: 8 },
  pdfBuyerName: { fontSize: 15, fontWeight: '700', color: '#111827' },
  pdfBuyerSub: { fontSize: 12, color: '#6b7280', marginTop: 2 },
  pdfTableHead: { flexDirection: 'row', backgroundColor: '#1a3728', borderRadius: 4, paddingHorizontal: 10, paddingVertical: 8, marginBottom: 2 },
  pdfTableHeadTxt: { fontSize: 11, fontWeight: '800', color: '#fff', textTransform: 'uppercase' },
  pdfTableRow: { flexDirection: 'row', paddingHorizontal: 10, paddingVertical: 9, borderRadius: 2 },
  pdfTableCell: { fontSize: 13, color: '#374151' },
  pdfTotalRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 4 },
  pdfTotalLabel: { fontSize: 14, fontWeight: '800', color: '#111827', letterSpacing: 1 },
  pdfTotalAmt: { fontSize: 20, fontWeight: '900', color: '#1a3728' },
  pdfPayLine: { fontSize: 13, color: '#374151', marginBottom: 5 },
  pdfPayKey: { fontWeight: '700', color: '#111827' },
  pdfNotes: { fontSize: 13, color: '#6b7280', lineHeight: 20 },
  pdfFooterBar: { marginTop: 32, borderTopWidth: 1, borderTopColor: '#e5e7eb', paddingTop: 12, alignItems: 'center' },
  pdfFooterTxt: { fontSize: 11, color: '#9ca3af' },
})
